#!/bin/bash

CP=asm-all-5.0.3.jar:bin
SRC=$(cat<<EOF
src/scala/bytecode/test/*.scala
src/scala/bytecode/test/dups/*.scala
src/scala/bytecode/test/ifs/*.scala
src/scala/bytecode/test/loops/*.scala
src/scala/bytecode/test/ternaries/*.scala
src/scala/bytecode/test/try_catches/*.scala
EOF
)

scalac -classpath $CP -d bin -deprecation -feature -sourcepath src -unchecked $SRC

