#!/bin/bash

CP=asm-all-5.0.3.jar:bin
SRC=$(cat<<EOF
src/scala/bytecode/asm/*.scala
src/scala/bytecode/*.scala
src/scala/bytecode/ast/*.scala
EOF
)

scalac -classpath $CP -d bin -deprecation -feature -sourcepath src -unchecked $SRC
